### ISSUE TITLE
Does not recognize lazyloader

### ISSUE THREAD

**Issue by liepumartins** [YellowLabTools/YellowLabTools#241]
Pages using https://github.com/verlok/lazyload gets penalized "Below the fold images" score.
Even when threshold is set to values <50px;
Using network log on any browser clearly shows images are being lazyloaded.

**Comment by gmetais** [comment]
Hi, thanks for the info.

It's kind of strange but it looks like this lazyloader is not compatible with the old version of Webkit used inside PhantomJS. Not sure what can be done about this, except waiting for the next version...

I've been seeing sometimes bugs with the one of the numerous ways to get the window height in JS and it could be the reason behind this bug.

**Comment by f3bruary** [comment]
I'm getting this on a project I created using Gridsome (vue.js), which has built in lazy loading.

**Comment by gmetais** [comment]
I've pushed a beta version of Yellow Lab Tools v2 online, do you mind checking if you still see this lazyloading issue?

**Comment by robinpoort** [comment]
Still a problem here on `Yellow Lab Tools v2 online` while using https://github.com/aFarkas/lazysizes on several websites. Not a super big deal since I know I'm using lazyloading but it'd still be nice to have it not affect the score 👍 

On a sidenote; [the lazyloader being suggested](https://github.com/vvo/lazyload):
```
This is the number of images displayed below the fold that could be lazy-loaded. This is an excellent way to accelerate the loading time of an heavy page.

I recommend using this lazyloader.
```

Is not active anymore. The developers suggest [Lozad](https://github.com/ApoorvSaxena/lozad.js/). Might be good to at least check if Lozad is being recognized properly and update the text accordingly? :-)

Anyways, thanks for the great tool!

**Comment by gmetais** [comment]
Thanks a lot @robinpoort!

I think I've managed to fix the bug. When the headless browser was taking a screenshot of the page, it was resizing the viewport to the full page's height. That was causing all images under the fold to load.

Would you mind testing again?

I've also changed the recommended library. Good catch!

**Comment by robinpoort** [comment]
Thanks @gmetais!

I can confirm that Yellow Lab is now recognizing the lazyloader!

Still affecting the score on the sites I built though since I choose to load a small 32px wide image (blurred using CSS) while images are being lazyloaded as this is a better effect for the end-user since they can see something already. However that is my own problem (Which I might be able to fix using data URI instead of actual images) :-)

Oh and cool to see  both Lozad as Lazysizes as recommendations :-)

Thanks again!

**Comment by gmetais** [comment]
Good news! Thanks a lot for your help!
