### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by PurpleBabar** [YellowLabTools/YellowLabTools#302]
Hi Gael :) 

Thanks for the great job with yellow lab tools :) I can see that there's not a lot of movement on the repository for now :/ would you be open to new maintainers ? Or an official fork ? Or an organization to maintain it ? 

Happy to talk about it with you if needed :)

cheerz

**Comment by gmetais** [comment]
After talking in private with @PurpleBabar, I'm switching the project to a "GitHub Organization". The new repository will be https://github.com/YellowLabTools/YellowLabTools.

The project will be easier to maintain and evolve. See you soon from the other side!

**Comment by gmetais** [comment]
Here we are!
If anyone owns a project around YellowLabTools, contact me if you want to transfer it to the organization (and join it).

**Comment by clemstoclems** [comment]
Hi Gaël,

I'am @PurpleBabar's coworker and we are working on a side project on wich we use a dockerize version of Yellowlabs. 
It would be nice to join the organization to contribute and become a maintainer :) 

Best regards

**Comment by gmetais** [comment]
Done!

**Comment by gmetais** [comment]
Hi @PurpleBabar and @clemstoclems,

I'm working on migrating the public instance to the cloud and I need to create a private repository with sensitive informations. I'm sorry, but I need to convert your access to "outside collaborators" :/

**Comment by ousamabenyounes** [comment]
hi @PurpleBabar and @clemstoclems 
I just saw that you are using a dockerized version of YLT. 
We juste published a YLT V2 docker that you can find here: https://github.com/ousamabenyounes/docker-yellowlabtools
If you want to help us to maintain it you're welcome.

Next step, we will need to make a multi stage docker image to be able to deliver a smallest container on dockerhub.

The actual version takes 1,3 go on your hard disk because (we are using alpine )

Regards,
Ousama.

**Comment by PurpleBabar** [comment]
@gmetais works fine for me :) 

@ousamabenyounes make a PR for the current repo :) (I would have some questions though about the use of a non privileged user and the use of the privilege option 🤔)

**Comment by clemstoclems** [comment]
Hi @gmetais :)
sorry for the late response.
 
no problem .

@ousamabenyounes nice ! i will take a look and will be glad to help you :)
