### ISSUE TITLE
https://yellowlab.tools/queue/fkezicxf19  -> test failed 

### ISSUE THREAD

**Issue by keroroyul** [YellowLabTools/YellowLabTools#306]
Cannot run test on 
https://yellowlab.tools/queue/fkezicxf19

for 

https://kr.iqos.com 

Could you help out on this?

**Comment by clemstoclems** [comment]
Hi,

Not sure how i can help you.The url you wrote is the queued job.
Your result is not queued anymore so the url give a 404 response.

When you run a test, you have to wait it to complete and then you will have an url for the results.

In your case, i tried to run a test but it failed because your website couldn' be loaded. (maybe because it doesnt support https, and you seems to have some disclaimers.)

**Comment by gmetais** [comment]
Hi @keroroyul, sorry for the late answer.

When I open your URL, I see 3 successive redirections, including one with JavaScript. YellowLabTools is not able to follow all these. Try testing the last URL directly: https://kr.iqos.com/ko/mobileverification. You can probably also add some cookies in the advanced settings, so that no redirection occurs.
