### ISSUE TITLE
The online server maybe stuck now.....

### ISSUE THREAD

**Issue by ZiRanSlash** [YellowLabTools/YellowLabTools#323]
I launched a test for my websites on two hours ago, but it stuck in "Load Pages and .......". I refresh this page and launch a new test and it shows "waitting behind 1 other tests". Two hours later, launch a new test it also show "waitting behind 14 other tests".
Meybe it is my fault, can you fix it? I feel very sorry for that.  TAT

**Comment by gmetais** [comment]
Hi @ZiRanSlash,

Thanks for reporting the issue. No worry, I'm currently beta-testing a new major version and I was expecting this kind of bugs. Could you just please avoid testing your webpage on the tool until I come back with a fix, so that other users have a chance to use it? I hope it will be quick!

Many thanks!

**Comment by ZiRanSlash** [comment]
Yes, I will avoid testing my website until it fixed. 
I'm looking forward to your new version and thank you very much!

**Comment by gmetais** [comment]
Hi @ZiRanSlash, you can retry.
The bug should be fixed now and the live beta testing of YLT v2 is restarting!
