### ISSUE TITLE
DOM max depth suggestion

### ISSUE THREAD

**Issue by robinpoort** [YellowLabTools/YellowLabTools#326]
Hi!

I know that the max DOM depth has been bumped form 10 elements in the past to 14 elements today but I'd still like to make a suggestion.

I've got a website that is using an SVG mask to mask avatar images. The last 4 elements in my max DOM depth are all part of the SVG: `svg defs mask image`. See: https://yellowlab.tools/result/fve0nec98v/rule/DOMelementMaxDepth

Might it be an option to stop counting the depth when an SVG is found? Or is that the single reason that the depth has been bumped to 14 in the first place?

Thanks!

**Comment by gmetais** [comment]
Hi @robinpoort,

From a browser's point of view, it seems to me that inline SVG sub-elements are interpreted just like DOM elements. You can change their style with CSS, access them with JS, and so on.

The max depth was increased because browsers and devices are faster and faster. They can handle complex pages more easily than 6 years ago.

I'll increase the threshold to 15 to anticipate this year's new devices :)

**Comment by robinpoort** [comment]
Hi @gmetais Thanks for the quick reply!

I see, fair point :)
